Ydate0/urls.py
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ydate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('',ydate,name='home'),

]

accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accountapp.views import blogin, AccountDetailView, AccountCreateView, YdateLogin

app_name = 'accountapp'

urlpatterns = [
    path('login/', YdateLogin.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('blogin/', blogin, name='blogin'),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import ydate, YONE, YTHREE, YTWO, RECOMMEND

app_name = 'articleapp'

urlpatterns = [
    path('list/', ydate, name='list'),
    path('recommend/<int:pk>',RECOMMEND.as_view(), name='recommend'),
    path('yone/<int:pk>', YONE.as_view(), name='yone'),
    path('ytwo/<int:pk>', YTWO.as_view(), name='ytwo'),
    path('ythree/<int:pk>', YTHREE.as_view(), name='ythree'),
    ]

accountapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class YMTI(AbstractUser):
    mem_no = models.IntegerField(null=True)
    mem_sex = models.TextField(null=True)
    mem_age = models.IntegerField(null=True)
    mem_loc = models.TextField(null=True)
    mem_birth_ddi = models.IntegerField(null=True)
    mate_blood = models.IntegerField(null=True)
    pf_ins_yn = models.TextField(null=True)
    mbti_code = models.TextField(null=True)
    food_cat = models.TextField(null=True)
    concn = models.FloatField(null=True)

accountapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accountapp.models import YMTI
from django.contrib.auth.forms import AuthenticationForm

class YMTISIGN(UserCreationForm):
  class Meta:
    model = YMTI
    fields = ['username', 'password1', 'password2']

accountapp/views.py
import csv

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, DetailView

from accountapp.forms import YMTISIGN
from accountapp.models import YMTI



class YdateLogin(LoginView):

    def get_success_url(self):
        return reverse('accountapp:detail',kwargs={'pk':self.request.user.pk})


class AccountCreateView(CreateView):
    model = YMTI
    form_class = YMTISIGN
    success_url = reverse_lazy('articleapp:list')
    template_name = 'create.html'


def blogin(request):
    return render(request, 'blogin.html')

class AccountDetailView(DetailView):
    model = YMTI
    context_object_name = 'target_user'
    template_name = 'detail.html'


## ymti회원 데이터를 YMTI 모델에 추가
# with open('static/data/profile_ymti_data_ver2/ymti_userdata.csv',newline='') as csvfile:
#     data_reader = csv.DictReader(csvfile)
#     for row in data_reader:
#         YMTI.objects.create(
#         username=row['mem_id'],
#         password= make_password(row['mem_no']),
#         mem_no = row['mem_no'],
#         mem_sex = row['mem_sex'],
#         mem_age = row['mem_age'],
#         mem_loc = row['mem_loc'],
#         mem_birth_ddi = row['mem_birth_ddi'],
#         mate_blood = row['mate_blood'],
#         pf_ins_yn = row['pf_ins_yn'],
#         mbti_code = row['mbti_code'],
#         food_cat =row['food_cat'],
#         concn =row['concn'],
#         )
# 비밀번호 암호화 관련 참고링크! -> make_password()
# https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#django.contrib.auth.hashers.PBKDF2PasswordHasher

accountapp/templates/blogin.html
{% extends 'base.html' %}
{% block content %}

 {% include 'star.html' %}
        <div class="blogin">
                 <a href="https://m.yeoboya.com/ymti/ymtiShareMain" target="_blank" class="ios-15">
                    <div class="wrapper">
                        <span class="blogin_ymti">
                            YMTI 검사하기</span>
                        <div class="circle circle-12"></div>
                        <div class="circle circle-11"></div>
                        <div class="circle circle-10"></div>
                        <div class="circle circle-9"></div>
                        <div class="circle circle-8"></div>
                        <div class="circle circle-7"></div>
                        <div class="circle circle-6"></div>
                        <div class="circle circle-5"></div>
                        <div class="circle circle-4"></div>
                        <div class="circle circle-3"></div>
                        <div class="circle circle-2"></div>
                        <div class="circle circle-1"></div>
                    </div>
                </a>
            <div>
                <a href="{% url 'accountapp:create' %}">
                   <div class="card">
                    나만의 보석 만나러 가기
                    </div>
                </a>
            </div>
        </div>

{% endblock %} 

accountapp/templates/create.html
    {% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <body>
        <div>
            {% include 'star.html' %}
            <form action="{% url 'accountapp:create' %}" method="post" class="createForm">{% csrf_token %}
                <span style="font-size: 35px">회원 가입</span>
                {% for field in form %}
            <div class="idForm">
                <label form="{{ field.id_for_label }}">{{ field.label }}</label>
                <input type="{{ field.field.widget.input_type }}" class="id"
                   id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}"/>
            </div>
            {% endfor %}
                {% if form.errors %}
                <span style="color: red; font-size: 1rem;font-weight: bold">필수 항목입니다</span>
                {% endif %}

                    <button type="submit" class="btn rounded-pill" onclick="button()">Create</button>
            </form>

        </div>
    </body>

{% endblock %}

accountapp/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    {% include 'star.html' %}
{% if user.is_authenticated %}
    {% if user == target_user %}
    <div class="detailForm">
        <div>
            <span style="font-size: 43px;">나의 보석</span>
                {#  본인 보석 알려주기!   #}
            <p>
                {% if target_user.mbti_code == 'ENFP' %}
                    <img src="../../static/ymti_jewerly/토파즈.png" class="detail_jewerly">
                    <h3>낙천적인 토파즈</h3>
                {% elif target_user.mbti_code == 'ENFJ' %}
                    <h3>배려감 넘치는 크리스탈</h3>
                    <img src="../../static/ymti_jewerly/크리스탈.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ENTJ' %}
                    <h3>사랑을 쟁취하는 에메랄드</h3>
                    <img src="../../static/ymti_jewerly/에메랄드.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ENTP' %}
                    <h3>생각이 톡톡 튀는 페리도트</h3>
                    <img src="../../static/ymti_jewerly/페리도트.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ESFJ' %}
                    <h3>포용하는 사파이어</h3>
                    <img src="../../static/ymti_jewerly/사파이어.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ESFP' %}
                    <h3>기쁨을 주는 쿤자이트</h3>
                    <img src="../../static/ymti_jewerly/쿤자이트.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ESTJ' %}
                    <h3>책임감의 대명사 터키석</h3>
                    <img src="../../static/ymti_jewerly/터키석.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ESTP' %}
                    <h3>자신감 넘치는 루벨라이트</h3>
                    <img src="../../static/ymti_jewerly/루벨라이트.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'INFJ' %}
                    <h3>신뢰 가득한 가넷</h3>
                    <img src="../../static/ymti_jewerly/가넷.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'INFP' %}
                    <h3>낭만적인 루비</h3>
                    <img src="../../static/ymti_jewerly/루비.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'INTJ' %}
                    <h3>능력있는 진주</h3>
                    <img src="../../static/ymti_jewerly/진주.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'INTP' %}
                    <h3>품격있는 다이아몬드</h3>
                    <img src="../../static/ymti_jewerly/다이아몬드.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ISFJ' %}
                    <h3>이해심 넘치는 투어멀린</h3>
                    <img src="../../static/ymti_jewerly/투어멀린.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ISFP' %}
                    <h3>정이 많은 라피스라줄리</h3>
                    <img src="../../static/ymti_jewerly/라피스라줄리.png" class="detail_jewerly">
                {% elif target_user.mbti_code == 'ISTJ' %}
                    <h3>조용히 강렬한 자수정</h3>
                    <img src="../../static/ymti_jewerly/자수정.png" class="detail_jewerly">
                {% elif food == 'ISTP' %}
                    <h3>상대를 존중하는 아쿠아마린</h3>
                    <img src="../../static/ymti_jewerly/아쿠아마린.png" class="detail_jewerly">
                {% endif %}
            </p>
        </div>
    </div>
            <div style="text-align:center; top:88%; left:41%; position:absolute; padding: 13px 10px; color:black;
            font-size: 20px;
                        width:280px; height:50px; border-radius:20px; background-color:rgba(248,248,255,0.58);">
            내짝꿍  만나러가기  &nbsp &nbsp &nbsp
                <a class="heart" href="{% url 'articleapp:recommend' pk=target_user.pk%}">
                </a>
            </div>

    {% else%}
    {% endif %}



{% endif %}
    {% endblock %}

accountapp/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <body>
    {% include 'star.html' %}
    <form action="" method="post" class="loginForm">{% csrf_token %}
        <span style="font-size: 35px">Login</span>
        {% for field in form %}
        <div class="idForm">
            <label form="{{ field.id_for_label }}">{{ field.label }}</label>
            <input type="{{ field.field.widget.input_type }}" class="id"
                   id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}"/>
        </div>
        {% endfor %}
        {% if form.errors %}
            <span style="color: red; font-size: 1rem;font-weight: bold">필수 항목입니다</span>
        {% endif %}

        <button type="submit" class="btn rounded-pill" onclick="button()">Log in</button>

    </form>

</body>

{% endblock %}