Ydate0/urls.py
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ydate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('',ydate,name='home'),

]

accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accountapp.views import blogin, AccountDetailView, AccountCreateView, YdateLogin

app_name = 'accountapp'

urlpatterns = [
    path('login/', YdateLogin.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('blogin/', blogin, name='blogin'),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import ydate, YONE, YTHREE, YTWO, RECOMMEND

app_name = 'articleapp'

urlpatterns = [
    path('list/', ydate, name='list'),
    path('recommend/<int:pk>',RECOMMEND.as_view(), name='recommend'),
    path('yone/<int:pk>', YONE.as_view(), name='yone'),
    path('ytwo/<int:pk>', YTWO.as_view(), name='ytwo'),
    path('ythree/<int:pk>', YTHREE.as_view(), name='ythree'),
    ]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

{% load static %}
{% include 'header.html' %}

{% block content %}
{% endblock %}





</html>

templates/cutyfire.html
<div class="pyro">
  <div class="before"></div>
  <div class="after"></div>
</div>
<style>
    body {
  margin: 0;
  padding: 0;
  background: rgba(0, 0, 0, 0);
  overflow: hidden;
}

.pyro > .before, .pyro > .after {
  position: absolute;
  width: 5px;
  height: 5px;
  border-radius: 50%;
  box-shadow: 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff, 0 0 #fff;
  -moz-animation: 1s bang ease-out infinite backwards, 1s gravity ease-in infinite backwards, 5s position linear infinite backwards;
  -webkit-animation: 1s bang ease-out infinite backwards, 1s gravity ease-in infinite backwards, 5s position linear infinite backwards;
  -o-animation: 1s bang ease-out infinite backwards, 1s gravity ease-in infinite backwards, 5s position linear infinite backwards;
  -ms-animation: 1s bang ease-out infinite backwards, 1s gravity ease-in infinite backwards, 5s position linear infinite backwards;
  animation: 1s bang ease-out infinite backwards, 1s gravity ease-in infinite backwards, 5s position linear infinite backwards;
}

.pyro > .after {
  -moz-animation-delay: 1.25s, 1.25s, 1.25s;
  -webkit-animation-delay: 1.25s, 1.25s, 1.25s;
  -o-animation-delay: 1.25s, 1.25s, 1.25s;
  -ms-animation-delay: 1.25s, 1.25s, 1.25s;
  animation-delay: 1.25s, 1.25s, 1.25s;
  -moz-animation-duration: 1.25s, 1.25s, 6.25s;
  -webkit-animation-duration: 1.25s, 1.25s, 6.25s;
  -o-animation-duration: 1.25s, 1.25s, 6.25s;
  -ms-animation-duration: 1.25s, 1.25s, 6.25s;
  animation-duration: 1.25s, 1.25s, 6.25s;
}

@-webkit-keyframes bang {
  to {
    box-shadow: -249px -107.6666666667px #ff0055, -85px -2.6666666667px #fff700, -52px 16.3333333333px #ff5500, 176px -85.6666666667px #9d00ff, 103px -49.6666666667px #ffd500, -68px 41.3333333333px #7300ff, 149px -161.6666666667px #00c8ff, 54px -209.6666666667px #8000ff, 4px 11.3333333333px #ff00d9, 125px -141.6666666667px fuchsia, 52px -221.6666666667px #ff003c, 134px -20.6666666667px #6600ff, 100px -61.6666666667px #00ff33, 58px -162.6666666667px #ae00ff, 155px -307.6666666667px #00ffee, -228px -46.6666666667px #ff00d5, 225px -384.6666666667px #ff00e6, 249px -104.6666666667px #eaff00, 110px -351.6666666667px #00ffb3, -202px -99.6666666667px #80ff00, 19px -9.6666666667px #2bff00, -29px -270.6666666667px #00f7ff, -35px -196.6666666667px #ff0073, 80px -30.6666666667px #2bff00, 109px -321.6666666667px #00ff6f, 197px -196.6666666667px #0077ff, -188px -277.6666666667px #48ff00, 148px -12.6666666667px #00ffe6, 133px -201.6666666667px #9900ff, -243px -225.6666666667px darkorange, -3px -374.6666666667px #7bff00, -208px -120.6666666667px #ff3700, 181px -240.6666666667px #ff5500, 165px -182.6666666667px #00ff1a, 119px -210.6666666667px #005eff, 198px -72.6666666667px #00ff55, -183px -144.6666666667px #1500ff, 167px -369.6666666667px #ff00c8, 101px -125.6666666667px #ff0011, 249px -291.6666666667px #ff00c8, 17px -193.6666666667px #ff0040, -240px 82.3333333333px #00ff04, -240px 71.3333333333px #00c8ff, 218px -296.6666666667px #00ff95, -42px -340.6666666667px #00b3ff, -218px -348.6666666667px #2b00ff, 54px -251.6666666667px #3700ff, -69px -397.6666666667px #55ff00, 153px -226.6666666667px #ff0091, 51px -311.6666666667px #73ff00, -100px -11.6666666667px #e6ff00;
  }
}
@-moz-keyframes bang {
  to {
    box-shadow: -249px -107.6666666667px #ff0055, -85px -2.6666666667px #fff700, -52px 16.3333333333px #ff5500, 176px -85.6666666667px #9d00ff, 103px -49.6666666667px #ffd500, -68px 41.3333333333px #7300ff, 149px -161.6666666667px #00c8ff, 54px -209.6666666667px #8000ff, 4px 11.3333333333px #ff00d9, 125px -141.6666666667px fuchsia, 52px -221.6666666667px #ff003c, 134px -20.6666666667px #6600ff, 100px -61.6666666667px #00ff33, 58px -162.6666666667px #ae00ff, 155px -307.6666666667px #00ffee, -228px -46.6666666667px #ff00d5, 225px -384.6666666667px #ff00e6, 249px -104.6666666667px #eaff00, 110px -351.6666666667px #00ffb3, -202px -99.6666666667px #80ff00, 19px -9.6666666667px #2bff00, -29px -270.6666666667px #00f7ff, -35px -196.6666666667px #ff0073, 80px -30.6666666667px #2bff00, 109px -321.6666666667px #00ff6f, 197px -196.6666666667px #0077ff, -188px -277.6666666667px #48ff00, 148px -12.6666666667px #00ffe6, 133px -201.6666666667px #9900ff, -243px -225.6666666667px darkorange, -3px -374.6666666667px #7bff00, -208px -120.6666666667px #ff3700, 181px -240.6666666667px #ff5500, 165px -182.6666666667px #00ff1a, 119px -210.6666666667px #005eff, 198px -72.6666666667px #00ff55, -183px -144.6666666667px #1500ff, 167px -369.6666666667px #ff00c8, 101px -125.6666666667px #ff0011, 249px -291.6666666667px #ff00c8, 17px -193.6666666667px #ff0040, -240px 82.3333333333px #00ff04, -240px 71.3333333333px #00c8ff, 218px -296.6666666667px #00ff95, -42px -340.6666666667px #00b3ff, -218px -348.6666666667px #2b00ff, 54px -251.6666666667px #3700ff, -69px -397.6666666667px #55ff00, 153px -226.6666666667px #ff0091, 51px -311.6666666667px #73ff00, -100px -11.6666666667px #e6ff00;
  }
}
@-o-keyframes bang {
  to {
    box-shadow: -249px -107.6666666667px #ff0055, -85px -2.6666666667px #fff700, -52px 16.3333333333px #ff5500, 176px -85.6666666667px #9d00ff, 103px -49.6666666667px #ffd500, -68px 41.3333333333px #7300ff, 149px -161.6666666667px #00c8ff, 54px -209.6666666667px #8000ff, 4px 11.3333333333px #ff00d9, 125px -141.6666666667px fuchsia, 52px -221.6666666667px #ff003c, 134px -20.6666666667px #6600ff, 100px -61.6666666667px #00ff33, 58px -162.6666666667px #ae00ff, 155px -307.6666666667px #00ffee, -228px -46.6666666667px #ff00d5, 225px -384.6666666667px #ff00e6, 249px -104.6666666667px #eaff00, 110px -351.6666666667px #00ffb3, -202px -99.6666666667px #80ff00, 19px -9.6666666667px #2bff00, -29px -270.6666666667px #00f7ff, -35px -196.6666666667px #ff0073, 80px -30.6666666667px #2bff00, 109px -321.6666666667px #00ff6f, 197px -196.6666666667px #0077ff, -188px -277.6666666667px #48ff00, 148px -12.6666666667px #00ffe6, 133px -201.6666666667px #9900ff, -243px -225.6666666667px darkorange, -3px -374.6666666667px #7bff00, -208px -120.6666666667px #ff3700, 181px -240.6666666667px #ff5500, 165px -182.6666666667px #00ff1a, 119px -210.6666666667px #005eff, 198px -72.6666666667px #00ff55, -183px -144.6666666667px #1500ff, 167px -369.6666666667px #ff00c8, 101px -125.6666666667px #ff0011, 249px -291.6666666667px #ff00c8, 17px -193.6666666667px #ff0040, -240px 82.3333333333px #00ff04, -240px 71.3333333333px #00c8ff, 218px -296.6666666667px #00ff95, -42px -340.6666666667px #00b3ff, -218px -348.6666666667px #2b00ff, 54px -251.6666666667px #3700ff, -69px -397.6666666667px #55ff00, 153px -226.6666666667px #ff0091, 51px -311.6666666667px #73ff00, -100px -11.6666666667px #e6ff00;
  }
}
@-ms-keyframes bang {
  to {
    box-shadow: -249px -107.6666666667px #ff0055, -85px -2.6666666667px #fff700, -52px 16.3333333333px #ff5500, 176px -85.6666666667px #9d00ff, 103px -49.6666666667px #ffd500, -68px 41.3333333333px #7300ff, 149px -161.6666666667px #00c8ff, 54px -209.6666666667px #8000ff, 4px 11.3333333333px #ff00d9, 125px -141.6666666667px fuchsia, 52px -221.6666666667px #ff003c, 134px -20.6666666667px #6600ff, 100px -61.6666666667px #00ff33, 58px -162.6666666667px #ae00ff, 155px -307.6666666667px #00ffee, -228px -46.6666666667px #ff00d5, 225px -384.6666666667px #ff00e6, 249px -104.6666666667px #eaff00, 110px -351.6666666667px #00ffb3, -202px -99.6666666667px #80ff00, 19px -9.6666666667px #2bff00, -29px -270.6666666667px #00f7ff, -35px -196.6666666667px #ff0073, 80px -30.6666666667px #2bff00, 109px -321.6666666667px #00ff6f, 197px -196.6666666667px #0077ff, -188px -277.6666666667px #48ff00, 148px -12.6666666667px #00ffe6, 133px -201.6666666667px #9900ff, -243px -225.6666666667px darkorange, -3px -374.6666666667px #7bff00, -208px -120.6666666667px #ff3700, 181px -240.6666666667px #ff5500, 165px -182.6666666667px #00ff1a, 119px -210.6666666667px #005eff, 198px -72.6666666667px #00ff55, -183px -144.6666666667px #1500ff, 167px -369.6666666667px #ff00c8, 101px -125.6666666667px #ff0011, 249px -291.6666666667px #ff00c8, 17px -193.6666666667px #ff0040, -240px 82.3333333333px #00ff04, -240px 71.3333333333px #00c8ff, 218px -296.6666666667px #00ff95, -42px -340.6666666667px #00b3ff, -218px -348.6666666667px #2b00ff, 54px -251.6666666667px #3700ff, -69px -397.6666666667px #55ff00, 153px -226.6666666667px #ff0091, 51px -311.6666666667px #73ff00, -100px -11.6666666667px #e6ff00;
  }
}
@keyframes bang {
  to {
    box-shadow: -249px -107.6666666667px #ff0055, -85px -2.6666666667px #fff700, -52px 16.3333333333px #ff5500, 176px -85.6666666667px #9d00ff, 103px -49.6666666667px #ffd500, -68px 41.3333333333px #7300ff, 149px -161.6666666667px #00c8ff, 54px -209.6666666667px #8000ff, 4px 11.3333333333px #ff00d9, 125px -141.6666666667px fuchsia, 52px -221.6666666667px #ff003c, 134px -20.6666666667px #6600ff, 100px -61.6666666667px #00ff33, 58px -162.6666666667px #ae00ff, 155px -307.6666666667px #00ffee, -228px -46.6666666667px #ff00d5, 225px -384.6666666667px #ff00e6, 249px -104.6666666667px #eaff00, 110px -351.6666666667px #00ffb3, -202px -99.6666666667px #80ff00, 19px -9.6666666667px #2bff00, -29px -270.6666666667px #00f7ff, -35px -196.6666666667px #ff0073, 80px -30.6666666667px #2bff00, 109px -321.6666666667px #00ff6f, 197px -196.6666666667px #0077ff, -188px -277.6666666667px #48ff00, 148px -12.6666666667px #00ffe6, 133px -201.6666666667px #9900ff, -243px -225.6666666667px darkorange, -3px -374.6666666667px #7bff00, -208px -120.6666666667px #ff3700, 181px -240.6666666667px #ff5500, 165px -182.6666666667px #00ff1a, 119px -210.6666666667px #005eff, 198px -72.6666666667px #00ff55, -183px -144.6666666667px #1500ff, 167px -369.6666666667px #ff00c8, 101px -125.6666666667px #ff0011, 249px -291.6666666667px #ff00c8, 17px -193.6666666667px #ff0040, -240px 82.3333333333px #00ff04, -240px 71.3333333333px #00c8ff, 218px -296.6666666667px #00ff95, -42px -340.6666666667px #00b3ff, -218px -348.6666666667px #2b00ff, 54px -251.6666666667px #3700ff, -69px -397.6666666667px #55ff00, 153px -226.6666666667px #ff0091, 51px -311.6666666667px #73ff00, -100px -11.6666666667px #e6ff00;
  }
}
@-webkit-keyframes gravity {
  to {
    transform: translateY(200px);
    -moz-transform: translateY(200px);
    -webkit-transform: translateY(200px);
    -o-transform: translateY(200px);
    -ms-transform: translateY(200px);
    opacity: 0;
  }
}
@-moz-keyframes gravity {
  to {
    transform: translateY(200px);
    -moz-transform: translateY(200px);
    -webkit-transform: translateY(200px);
    -o-transform: translateY(200px);
    -ms-transform: translateY(200px);
    opacity: 0;
  }
}
@-o-keyframes gravity {
  to {
    transform: translateY(200px);
    -moz-transform: translateY(200px);
    -webkit-transform: translateY(200px);
    -o-transform: translateY(200px);
    -ms-transform: translateY(200px);
    opacity: 0;
  }
}
@-ms-keyframes gravity {
  to {
    transform: translateY(200px);
    -moz-transform: translateY(200px);
    -webkit-transform: translateY(200px);
    -o-transform: translateY(200px);
    -ms-transform: translateY(200px);
    opacity: 0;
  }
}
@keyframes gravity {
  to {
    transform: translateY(200px);
    -moz-transform: translateY(200px);
    -webkit-transform: translateY(200px);
    -o-transform: translateY(200px);
    -ms-transform: translateY(200px);
    opacity: 0;
  }
}
@-webkit-keyframes position {
  0%, 19.9% {
    margin-top: 10%;
    margin-left: 40%;
  }
  20%, 39.9% {
    margin-top: 40%;
    margin-left: 30%;
  }
  40%, 59.9% {
    margin-top: 20%;
    margin-left: 70%;
  }
  60%, 79.9% {
    margin-top: 30%;
    margin-left: 20%;
  }
  80%, 99.9% {
    margin-top: 30%;
    margin-left: 80%;
  }
}
@-moz-keyframes position {
  0%, 19.9% {
    margin-top: 10%;
    margin-left: 40%;
  }
  20%, 39.9% {
    margin-top: 40%;
    margin-left: 30%;
  }
  40%, 59.9% {
    margin-top: 20%;
    margin-left: 70%;
  }
  60%, 79.9% {
    margin-top: 30%;
    margin-left: 20%;
  }
  80%, 99.9% {
    margin-top: 30%;
    margin-left: 80%;
  }
}
@-o-keyframes position {
  0%, 19.9% {
    margin-top: 10%;
    margin-left: 40%;
  }
  20%, 39.9% {
    margin-top: 40%;
    margin-left: 30%;
  }
  40%, 59.9% {
    margin-top: 20%;
    margin-left: 70%;
  }
  60%, 79.9% {
    margin-top: 30%;
    margin-left: 20%;
  }
  80%, 99.9% {
    margin-top: 30%;
    margin-left: 80%;
  }
}
@-ms-keyframes position {
  0%, 19.9% {
    margin-top: 10%;
    margin-left: 40%;
  }
  20%, 39.9% {
    margin-top: 40%;
    margin-left: 30%;
  }
  40%, 59.9% {
    margin-top: 20%;
    margin-left: 70%;
  }
  60%, 79.9% {
    margin-top: 30%;
    margin-left: 20%;
  }
  80%, 99.9% {
    margin-top: 30%;
    margin-left: 80%;
  }
}
@keyframes position {
  0%, 19.9% {
    margin-top: 10%;
    margin-left: 40%;
  }
  20%, 39.9% {
    margin-top: 40%;
    margin-left: 30%;
  }
  40%, 59.9% {
    margin-top: 20%;
    margin-left: 70%;
  }
  60%, 79.9% {
    margin-top: 30%;
    margin-left: 20%;
  }
  80%, 99.9% {
    margin-top: 30%;
    margin-left: 80%;
  }
}
</style>

templates/firetest.html
{% load static %}

    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/329180/Stage%400.1.4.js"></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/329180/MyMath.js"></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/329180/fscreen%401.0.1.js"></script>
    <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-1b93190375e9ccc259df3a57c1abc0e64599724ae30d7ea4c6877eb615f89387.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'test.css' %}">

    <!-- SVG Spritesheet -->
<div style="height: 0; width: 0; position: absolute; ">
                                    {#    visibility: hidden;#}
	<svg xmlns="http://www.w3.org/2000/svg">
		<symbol id="icon-play" viewBox="0 0 24 24">
			<path d="M8 5v14l11-7z"/>
		</symbol>
		<symbol id="icon-pause" viewBox="0 0 24 24">
			<path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/>
		</symbol>
		<symbol id="icon-close" viewBox="0 0 24 24">
			<path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
		</symbol>
		<symbol id="icon-settings" viewBox="0 0 24 24">
			<path d="M19.43 12.98c.04-.32.07-.64.07-.98s-.03-.66-.07-.98l2.11-1.65c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.3-.61-.22l-2.49 1c-.52-.4-1.08-.73-1.69-.98l-.38-2.65C14.46 2.18 14.25 2 14 2h-4c-.25 0-.46.18-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1c-.23-.09-.49 0-.61.22l-2 3.46c-.13.22-.07.49.12.64l2.11 1.65c-.04.32-.07.65-.07.98s.03.66.07.98l-2.11 1.65c-.19.15-.24.42-.12.64l2 3.46c.12.22.39.3.61.22l2.49-1c.52.4 1.08.73 1.69.98l.38 2.65c.03.24.24.42.49.42h4c.25 0 .46-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.23.09.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64l-2.11-1.65zM12 15.5c-1.93 0-3.5-1.57-3.5-3.5s1.57-3.5 3.5-3.5 3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5z"/>
		</symbol>
		<symbol id="icon-sound-on" viewBox="0 0 24 24">
			<path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3c0-1.77-1.02-3.29-2.5-4.03v8.05c1.48-.73 2.5-2.25 2.5-4.02zM14 3.23v2.06c2.89.86 5 3.54 5 6.71s-2.11 5.85-5 6.71v2.06c4.01-.91 7-4.49 7-8.77s-2.99-7.86-7-8.77z"/>
		</symbol>
		<symbol id="icon-sound-off" viewBox="0 0 24 24">
			<path d="M16.5 12c0-1.77-1.02-3.29-2.5-4.03v2.21l2.45 2.45c.03-.2.05-.41.05-.63zm2.5 0c0 .94-.2 1.82-.54 2.64l1.51 1.51C20.63 14.91 21 13.5 21 12c0-4.28-2.99-7.86-7-8.77v2.06c2.89.86 5 3.54 5 6.71zM4.27 3L3 4.27 7.73 9H3v6h4l5 5v-6.73l4.25 4.25c-.67.52-1.42.93-2.25 1.18v2.06c1.38-.31 2.63-.95 3.69-1.81L19.73 21 21 19.73l-9-9L4.27 3zM12 4L9.91 6.09 12 8.18V4z"/>
		</symbol>
	</svg>
</div>

<!-- App -->
<div class="container">
	<div class="loading-init">
		<div class="loading-init__header">Loading</div>
		<div class="loading-init__status">Assembling Shells</div>
	</div>
	<div class="stage-container remove">
		<div class="canvas-container">
			<canvas id="trails-canvas"></canvas>
			<canvas id="main-canvas"></canvas>
		</div>

		<div class="menu hide">
			<div class="menu__inner-wrap">
				<div class="btn btn--bright close-menu-btn">
					<svg fill="white" width="24" height="24"><use href="#icon-close" xlink:href="#icon-close"></use></svg>
				</div>
{#				<div class="menu__header">Settings</div>#}
{#				<div class="menu__subheader">For more info, click any label.</div>#}
				<form>
					<div class="form-option form-option--select">
						<label class="shell-type-label">Shell Type</label>
						<select class="shell-type"></select>
					</div>
					<div class="form-option form-option--select">
						<label class="shell-size-label">Shell Size</label>
						<select class="shell-size"></select>
					</div>
					<div class="form-option form-option--select">
						<label class="quality-ui-label">Quality</label>
						<select class="quality-ui"></select>
					</div>
					<div class="form-option form-option--select">
						<label class="sky-lighting-label">Sky Lighting</label>
						<select class="sky-lighting"></select>
					</div>
					<div class="form-option form-option--select">
						<label class="scaleFactor-label">Scale</label>
						<select class="scaleFactor"></select>
					</div>
					<div class="form-option form-option--checkbox">
						<label class="auto-launch-label">Auto Fire</label>
						<input class="auto-launch" type="checkbox" />
					</div>
					<div class="form-option form-option--checkbox form-option--finale-mode">
						<label class="finale-mode-label">Finale Mode</label>
						<input class="finale-mode" type="checkbox" />
					</div>
					<div class="form-option form-option--checkbox">
						<label class="hide-controls-label">Hide Controls</label>
						<input class="hide-controls" type="checkbox" />
					</div>
					<div class="form-option form-option--checkbox form-option--fullscreen">
						<label class="fullscreen-label">Fullscreen</label>
						<input class="fullscreen" type="checkbox" />
					</div>
					<div class="form-option form-option--checkbox">
						<label class="long-exposure-label">Open Shutter</label>
						<input class="long-exposure" type="checkbox" />
					</div>
				</form>
{#				<div class="credits">#}
{#					Passionately built by <a href="https://cmiller.tech/" target="_blank">Caleb Miller</a>.#}
{#				</div>#}
			</div>
		</div>
	</div>
	<div class="help-modal">
		<div class="help-modal__overlay"></div>
		<div class="help-modal__dialog">
			<div class="help-modal__header"></div>
			<div class="help-modal__body"></div>
			<button type="button" class="help-modal__close-btn">Close</button>
		</div>
	</div>
</div>

    <script src="{% static 'test.js' %}"></script>

templates/footer.html
<div class="text-center">
    <div>
        <span class="mx-2">문의</span>
        <a href="http://www.yeoboyacorp.com/2021/main.html" target="_blank">(주)여보야</a>
    </div>
    <div>
        <h6 style="color:ghostwhite">copyright@여만추 All rights are reserved.</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>여만추</title>

    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#   HEADER FONT #}
    {#  cafe24  font#}
    <link href="https://webfontworld.github.io/cafe24/Cafe24Oneprettynight.css" rel="stylesheet">

    {# Gamja+flower font  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet">

    {# sunflower font #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap" rel="stylesheet">

    {#    static link#}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {#  kakao#}
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>

</head>

templates/header.html
<div class="text-center">
    <div style="margin: 1rem 0; font-size: 20px;">
        {% if user.is_authenticated %}
         <h1>
            <a href="{% url 'articleapp:list' %}">
                여만추
            </a>
        </h1>
        <span class="mw-500">
            당신을 위한
        </span>
        {% else %}
         <h1>
            <a href="{% url 'articleapp:list' %}">
                여만추
            </a>
        </h1>
        <span class="mw-500">
            당신을 위한
        </span>
        {% endif %}

    </div>

    {% if user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accountapp:logout' %}">
                Logout
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                Mypage
            </a>
        </span>
    {% endif %}

</div>