Ydate0/urls.py
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ydate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('',ydate,name='home'),

]

accountapp/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accountapp.views import blogin, AccountDetailView, AccountCreateView, YdateLogin

app_name = 'accountapp'

urlpatterns = [
    path('login/', YdateLogin.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('blogin/', blogin, name='blogin'),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import ydate, YONE, YTHREE, YTWO, RECOMMEND

app_name = 'articleapp'

urlpatterns = [
    path('list/', ydate, name='list'),
    path('recommend/<int:pk>',RECOMMEND.as_view(), name='recommend'),
    path('yone/<int:pk>', YONE.as_view(), name='yone'),
    path('ytwo/<int:pk>', YTWO.as_view(), name='ytwo'),
    path('ythree/<int:pk>', YTHREE.as_view(), name='ythree'),
    ]

articleapp/models.py
from django.db import models

# Create your models here.

articleapp/views.py
from django.shortcuts import render

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic import DetailView


from accountapp.models import YMTI

## 회원 추천을 위한 Recommendation_System파일 호출
from static.Recommendation_System2 import *
## 데이트코스 추천을 위한 dating_course.py파일 호출
from static.dating_course2 import *



def ydate(request):
    return render(request,'list.html')


class RECOMMEND(DetailView):
    model = YMTI
    context_object_name = 'target'
    template_name = 'recommend.html'

    # 첫 번째 추천(음식)
    def food(self):
        user = self.request.user
        mem_id = user.mem_no
        food = find_food_person(mem_id, 1)['mbti_code']
        return food
    # 두 번째 추천(로그기반)
    def log(self):
        user = self.request.user
        mem_id = user.mem_no
        log = find_log(mem_id,1)['mbti_code']
        return log
    # 세 번째 추천(YMTI)
    def ymti_recommend(self):
        user = self.request.user
        mem_id = user.mem_no
        df_ymti = find_ymti(mem_id,30)
        df_ymti = df_ymti.sort_values(by='concn', axis=0,ascending=False)
        ymti_recommend = df_ymti[:1]['mbti_code']
        return ymti_recommend




## 1. 첫 번째 사람에 대한 장소,음식점 추천(음식 기반 사람 추천)
class YONE(DetailView):
    model = YMTI
    context_object_name = 'target_yone'
    template_name = 'yone.html'

    def yone_place_date(self):
        user = self.request.user
        mem_id = user.mem_no
        yone_place_date = first_dating_course(mem_id,1)
        yone_place_list = []
        for i in yone_place_date:
            yone_place_list.append(i)
        return yone_place_list[0]
    def yone_place_date_link(self):
        user = self.request.user
        mem_id = user.mem_no
        yone_place_date = first_dating_course(mem_id,1)
        yone_place_list = []
        for i in yone_place_date:
            yone_place_list.append(i)
        return yone_place_list[1]
    def yone_place_date_column(self):
        user = self.request.user
        mem_id = user.mem_no
        yone_place_date = first_dating_course(mem_id, 1)
        yone_place_list = []
        for i in yone_place_date:
            yone_place_list.append(i)
        return yone_place_list[2]

    def yone_food_date(self):
        user = self.request.user
        mem_id = user.mem_no
        yone_food_date = first_food_course(mem_id,1)
        yone_food_list = []
        for i in yone_food_date:
            yone_food_list.append(i)
        return yone_food_list[0]
    def yone_food_date_link(self):
        user = self.request.user
        mem_id = user.mem_no
        yone_food_date = first_food_course(mem_id,1)
        yone_food_list = []
        for i in yone_food_date:
            yone_food_list.append(i)
        return yone_food_list[1]
    def yone_food_date_column(self):
        user = self.request.user
        mem_id = user.mem_no
        yone_food_date = first_food_course(mem_id,1)
        yone_food_list = []
        for i in yone_food_date:
            yone_food_list.append(i)
        return yone_food_list[-1]



## 2. 두 번째 사람에 대한 장소, 음식점 추천(로그 기반 사람 추천)
class YTWO(DetailView):
    model = YMTI
    context_object_name = 'target_ytwo'
    template_name = 'ytwo.html'

    def ytwo_place_date(self):
        user = self.request.user
        mem_id = user.mem_no
        ytwo_place_date = second_dating_course(mem_id,1)
        ytwo_place_list = []
        for i in ytwo_place_date:
            ytwo_place_list.append(i)
        return ytwo_place_list[0]
    def ytwo_place_date_link(self):
        user = self.request.user
        mem_id = user.mem_no
        ytwo_place_date = second_dating_course(mem_id,1)
        ytwo_place_list = []
        for i in ytwo_place_date:
            ytwo_place_list.append(i)
        return ytwo_place_list[1]
    def ytwo_place_date_column(self):
        user = self.request.user
        mem_id = user.mem_no
        ytwo_place_date = second_dating_course(mem_id,1)
        ytwo_place_list = []
        for i in ytwo_place_date:
            ytwo_place_list.append(i)
        return ytwo_place_list[2]

    def ytwo_food_date(self):
        user = self.request.user
        mem_id = user.mem_no
        ytwo_food_date = second_food_course(mem_id,1)
        ytwo_food_list = []
        for i in ytwo_food_date:
            ytwo_food_list.append(i)
        return ytwo_food_list[0]
    def ytwo_food_date_link(self):
        user = self.request.user
        mem_id = user.mem_no
        ytwo_food_date = second_food_course(mem_id,1)
        ytwo_food_list = []
        for i in ytwo_food_date:
            ytwo_food_list.append(i)
        return ytwo_food_list[1]
    def ytwo_food_date_column(self):
        user = self.request.user
        mem_id = user.mem_no
        ytwo_food_date = second_food_course(mem_id,1)
        ytwo_food_list = []
        for i in ytwo_food_date:
            ytwo_food_list.append(i)
        return ytwo_food_list[-1]



## 3. 세 번째 사람에 대한 장소, 음식점 추천(YMTI 기반 사람 추천)
class YTHREE(DetailView):
    model = YMTI
    context_object_name = 'target_ythree'
    template_name = 'ythree.html'

    def ythree_place_date(self):
        user = self.request.user
        mem_id = user.mem_no
        ythree_place_date = third_dating_course(mem_id,1)
        ythree_place_list = []
        for i in ythree_place_date:
            ythree_place_list.append(i)
        return ythree_place_list[0]
    def ythree_place_date_link(self):
        user = self.request.user
        mem_id = user.mem_no
        ythree_place_date = third_dating_course(mem_id,1)
        ythree_place_list = []
        for i in ythree_place_date:
            ythree_place_list.append(i)
        return ythree_place_list[1]
    def ythree_place_date_column(self):
        user = self.request.user
        mem_id = user.mem_no
        ythree_place_date = third_dating_course(mem_id,1)
        ythree_place_list = []
        for i in ythree_place_date:
            ythree_place_list.append(i)
        return ythree_place_list[2]

    def ythree_food_date(self):
        user = self.request.user
        mem_id = user.mem_no
        ythree_food_date = third_food_course(mem_id,1)
        ythree_food_list = []
        for i in ythree_food_date:
            ythree_food_list.append(i)
        return ythree_food_list[0]
    def ythree_food_date_link(self):
        user = self.request.user
        mem_id = user.mem_no
        ythree_food_date = third_food_course(mem_id,1)
        ythree_food_list = []
        for i in ythree_food_date:
            ythree_food_list.append(i)
        return ythree_food_list[1]
    def ythree_food_date_column(self):
        user = self.request.user
        mem_id = user.mem_no
        ythree_food_date = third_food_course(mem_id,1)
        ythree_food_list = []
        for i in ythree_food_date:
            ythree_food_list.append(i)
        return ythree_food_list[-1]

articleapp/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<body>
        {% if user.is_authenticated %}
        {% include 'star.html' %}
        <div class="logo"><b>L<span>o</span><span>v</span>e</b></div>

      {% else %}
        {% include 'star.html' %}
    <div class="y_list">
    <a href="{% url 'accountapp:login' %}" class="m-5">
    <h1 class="article_image">MEMBER</h1>
    </a>
    <a href="{% url 'accountapp:blogin' %}" class="m-5 b-5">
    <h1 class="article_image2">YMTI</h1>
    </a>
    </div>

      {% endif %}


</body>
{% endblock %}

articleapp/templates/yone.html
{% extends 'base.html' %}
{% block content %}
    {% include 'star.html' %}
{% if user.is_authenticated %}
    {% if user == target_yone%}
        <div class="place_date">
            <h5 style="font-weight: bold;"> ♡ 함께하기 딱 좋은 이색 데이트 ♡ </h5>
                    {% if view.yone_place_date_column == 'inside' %}
                        <img src="../../static/데이트코스/실내2.png" class="place_dateimg">
                    {% elif view.yone_place_date_column == 'outside' %}
                        <img src="../../static/데이트코스/야외.jpg" class="place_dateimg">
                    {% endif %}
                <h4>{{ view.yone_place_date }}</h4>
                <a href="{{ view.yone_place_date_link }}" target="_blank"><span class="card_date">LINK</span></a>

        </div>
        <div class="food_date">
            <h5 style="font-weight: bold;"> ♡ 취향 맞춤 식당 ♡ </h5>
                    {% if view.yone_food_date_column == 'western' %}
                        <img src="../../static/데이트코스/양식2.jpg" class="place_dateimg">
                    {% elif view.yone_food_date_column == 'chinese' %}
                        <img src="../../static/데이트코스/중식.jpg" class="place_dateimg">
                    {% elif view.yone_food_date_column == 'japanese' %}
                        <img src="../../static/데이트코스/일식.jpg" class="place_dateimg">
                    {% elif view.yone_food_date_column == 'korean' %}
                        <img src="../../static/데이트코스/한식.png" class="place_dateimg">
                    {% elif view.yone_food_date_column == 'dessert' %}
                        <img src="../../static/데이트코스/디저트.png" class="place_dateimg">
                    {% elif view.yone_food_date_column == 'etc' %}
                        <img src="../../static/데이트코스/한식4.jpg" class="place_dateimg">
                    {% endif %}
                <h4>{{ view.yone_food_date }}</h4>
                <a href="{{ view.yone_food_date_link }}" target="_blank"><span class="card_date">LINK</span></a>
        </div>
        <div style="text-align: center;margin-top: 32rem;">
                <p>
                    <a id="btnTwitter" href="javascript:shareTwitter();">
                        <img src="/static/share_img/twitter_img.png" width=36 alt="Twitter">
                    </a>
                    <a id="btnFacebook" href="javascript:shareFacebook();">
                        <img src="/static/share_img/facebook_img.png" width=36 alt="Facebook">
                    </a>
                    <a id="btnKakao" href="javascript:shareKakao();">
                        <img src="/static/share_img/kakao_img.jpg" width=36 alt="Kakaotalk">
                    </a>
                            <script>
                            function shareTwitter() {
                                var sendText = "여만추"; // 전달할 텍스트
                                var sendUrl = "http://127.0.0.1:1021/articles/list/"; // 전달할 URL
                                window.open("https://twitter.com/intent/tweet?text=" + sendText + "&url=" + sendUrl);
                                    }
                            function shareFacebook() {
                                var sendUrl = "http://127.0.0.1:1021/articles/list/"; // 전달할 URL
                                window.open("http://www.facebook.com/sharer/sharer.php?u=" + sendUrl);
                                    }
                            function shareKakao() {
                              // 사용할 앱의 JavaScript 키 설정
                              Kakao.init('6119304fc2852939a02d1c268ece820f');
                              // 카카오링크 버튼 생성
                              Kakao.Link.createDefaultButton({
                                container: '#btnKakao', // 카카오공유버튼ID
                                objectType: 'feed',
                                content: {
                                  title: "여만추", // 보여질 제목
                                  description: "당신을 위한", // 보여질 설명
                                  imageUrl: "https://cdn.pixabay.com/photo/2015/10/16/19/18/balloon-991680_960_720.jpg", // 콘텐츠 URL
                                  link: {
                                     webUrl: "http://127.0.0.1:1021/"
                                  }
                                }
                              });
                                }
                            </script>
                </p>
        </div>
    {% else%}
        ??
    {% endif %}



{% endif %}
{% endblock %}

articleapp/templates/ythree.html
{% extends 'base.html' %}
{% block content %}
    {% include 'star.html' %}
{% if user.is_authenticated %}
    {% if user == target_ythree %}
        <div class="place_date">
            <h5 style="font-weight: bold;"> ♡ 함께하기 딱 좋은 이색 데이트 ♡ </h5>
                    {% if view.ythree_place_date_column == 'inside' %}
                        <img src="../../static/데이트코스/실내2.png" class="place_dateimg">
                    {% elif view.ythree_place_date_column == 'outside' %}
                        <img src="../../static/데이트코스/야외2.jpg" class="place_dateimg">
                    {% endif %}
                <h4>{{ view.ythree_place_date }}</h4>
                <a href="{{ view.ythree_place_date_link }}" target="_blank"><span class="card_date">LINK</span></a>
        </div>
        <div class="food_date">
            <h5 style="font-weight: bold;"> ♡ 취향 맞춤 식당 ♡ </h5>
                    {% if view.ythree_food_date_column == 'western' %}
                        <img src="../../static/데이트코스/양식2.jpg" class="place_dateimg">
                    {% elif view.ythree_food_date_column == 'chinese' %}
                        <img src="../../static/데이트코스/중식.jpg" class="place_dateimg">
                    {% elif view.ythree_food_date_column == 'japanese' %}
                        <img src="../../static/데이트코스/일식.jpg" class="place_dateimg">
                    {% elif view.ythree_food_date_column == 'korean' %}
                        <img src="../../static/데이트코스/한식.png" class="place_dateimg">
                    {% elif view.ythree_food_date_column == 'dessert' %}
                        <img src="../../static/데이트코스/디저트.png" class="place_dateimg">
                    {% elif view.ythree_food_date_column == 'etc' %}
                        <img src="../../static/데이트코스/한식4.jpg" class="place_dateimg">
                    {% endif %}
                <h4>{{ view.ythree_food_date }}</h4>
                <a href="{{ view.ythree_food_date_link }}" target="_blank"><span class="card_date">LINK</span></a>
        </div>
            <div style="text-align: center;margin-top: 32rem;">
                <p>
                    <a id="btnTwitter" href="javascript:shareTwitter();">
                        <img src="/static/share_img/twitter_img.png" width=36 alt="Twitter">
                    </a>
                    <a id="btnFacebook" href="javascript:shareFacebook();">
                        <img src="/static/share_img/facebook_img.png" width=36 alt="Facebook">
                    </a>
                    <a id="btnKakao" href="javascript:shareKakao();">
                        <img src="/static/share_img/kakao_img.jpg" width=36 alt="Kakaotalk">
                    </a>
                            <script>
                            function shareTwitter() {
                                var sendText = "여만추"; // 전달할 텍스트
                                var sendUrl = "http://127.0.0.1:1021/articles/list/"; // 전달할 URL
                                window.open("https://twitter.com/intent/tweet?text=" + sendText + "&url=" + sendUrl);
                                    }
                            function shareFacebook() {
                                var sendUrl = "http://127.0.0.1:1021/articles/list/"; // 전달할 URL
                                window.open("http://www.facebook.com/sharer/sharer.php?u=" + sendUrl);
                                    }
                            function shareKakao() {
                              // 사용할 앱의 JavaScript 키 설정
                              Kakao.init('6119304fc2852939a02d1c268ece820f');
                              // 카카오링크 버튼 생성
                              Kakao.Link.createDefaultButton({
                                container: '#btnKakao', // 카카오공유버튼ID
                                objectType: 'feed',
                                content: {
                                  title: "여만추", // 보여질 제목
                                  description: "당신을 위한", // 보여질 설명
                                  imageUrl: "https://cdn.pixabay.com/photo/2015/10/16/19/18/balloon-991680_960_720.jpg", // 콘텐츠 URL
                                  link: {
                                     webUrl: "http://127.0.0.1:1021/"
                                  }
                                }
                              });
                                }
                            </script>
                </p>
            </div>



    {% else%}
    {% endif %}


{% endif %}
{% endblock %}

articleapp/templates/ytwo.html
{% extends 'base.html' %}
{% block content %}
    {% include 'star.html' %}
{% if user.is_authenticated %}
    {% if user == target_ytwo %}
        <div class="place_date">
            <h5 style="font-weight: bold;"> ♡ 함께하기 딱 좋은 이색 데이트 ♡ </h5>
                {% if view.ytwo_place_date_column == 'inside' %}
                        <img src="../../static/데이트코스/실내2.png" class="place_dateimg">
                    {% elif view.ytwo_place_date_column == 'outside' %}
                        <img src="../../static/데이트코스/야외.jpg" class="place_dateimg">
                    {% endif %}
                <h4>{{ view.ytwo_place_date }}</h4>
                <a href="{{ view.ytwo_place_date_link }}" target="_blank"><span class="card_date">LINK</span></a>
        </div>
        <div class="food_date">
            <h5 style="font-weight: bold;"> ♡ 취향 맞춤 식당 ♡ </h5>
                    {% if view.ytwo_food_date_column == 'western' %}
                        <img src="../../static/데이트코스/양식2.jpg" class="place_dateimg">
                    {% elif view.ytwo_food_date_column == 'chinese' %}
                        <img src="../../static/데이트코스/중식.jpg" class="place_dateimg">
                    {% elif view.ytwo_food_date_column == 'japanese' %}
                        <img src="../../static/데이트코스/일식.jpg" class="place_dateimg">
                    {% elif view.ytwo_food_date_column == 'korean' %}
                        <img src="../../static/데이트코스/한식.png" class="place_dateimg">
                    {% elif view.ytwo_food_date_column == 'dessert' %}
                        <img src="../../static/데이트코스/디저트.png" class="place_dateimg">
                    {% elif view.ytwo_food_date_column == 'etc' %}
                        <img src="../../static/데이트코스/한식4.jpg" class="place_dateimg">
                    {% endif %}
                <h4>{{ view.ytwo_food_date }}</h4>
                <a href="{{ view.ytwo_food_date_link }}" target="_blank"><span class="card_date">LINK</span></a>
        </div>
        <div style="text-align: center;margin-top: 32rem;">
                <p>
                    <a id="btnTwitter" href="javascript:shareTwitter();">
                        <img src="/static/share_img/twitter_img.png" width=36 alt="Twitter">
                    </a>
                    <a id="btnFacebook" href="javascript:shareFacebook();">
                        <img src="/static/share_img/facebook_img.png" width=36 alt="Facebook">
                    </a>
                    <a id="btnKakao" href="javascript:shareKakao();">
                        <img src="/static/share_img/kakao_img.jpg" width=36 alt="Kakaotalk">
                    </a>
                            <script>
                            function shareTwitter() {
                                var sendText = "여만추"; // 전달할 텍스트
                                var sendUrl = "http://127.0.0.1:1021/articles/list/"; // 전달할 URL
                                window.open("https://twitter.com/intent/tweet?text=" + sendText + "&url=" + sendUrl);
                                    }
                            function shareFacebook() {
                                var sendUrl = "http://127.0.0.1:1021/articles/list/"; // 전달할 URL
                                window.open("http://www.facebook.com/sharer/sharer.php?u=" + sendUrl);
                                    }
                            function shareKakao() {
                              // 사용할 앱의 JavaScript 키 설정
                              Kakao.init('6119304fc2852939a02d1c268ece820f');
                              // 카카오링크 버튼 생성
                              Kakao.Link.createDefaultButton({
                                container: '#btnKakao', // 카카오공유버튼ID
                                objectType: 'feed',
                                content: {
                                  title: "여만추", // 보여질 제목
                                  description: "당신을 위한", // 보여질 설명
                                  imageUrl: "https://cdn.pixabay.com/photo/2015/10/16/19/18/balloon-991680_960_720.jpg", // 콘텐츠 URL
                                  link: {
                                     webUrl: "http://127.0.0.1:1021/"
                                  }
                                }
                              });
                                }
                            </script>
                </p>
        </div>

    {% else%}
    {% endif %}

{% endif %}
{% endblock %}